Update CA1068 to handle api_surface option
dotnet/roslyn-analyzers pull request #4474
Opened 2020-12-01 10:45 UTC by Evangelink

Fix #2851

**/!\ BREAKING CHANGE /!\**

2020-12-01 14:31 UTC, mavasani commented on src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs
> +                    if (!symbolContext.Options.MatchesConfiguredVisibility(Rule, methodSymbol, symbolContext.Compilation, symbolContext.CancellationToken))
I think we should not alter default semantics of this analyzer - it should flag all APIs by default, but end users can configure it to only configure specific API surfaces.
```suggestion
                    if (!symbolContext.Options.MatchesConfiguredVisibility(Rule, methodSymbol, symbolContext.Compilation, symbolContext.CancellationToken, defaultRequiredVisibility: SymbolVisibilityGroup.All))
```

2020-12-01 14:31 UTC, mavasani commented on src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs
> +public class T
The changes to existing tests should be reverted.

2020-12-01 14:34 UTC, mavasani commented on src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs
> +        [InlineData("public", "dotnet_code_quality.api_surface = public")]
Can we add a scenarios to the new tests with empty editorconfig and verify it flags all accessibility APIs?

2020-12-01 14:34 UTC, mavasani requested changes
Lets ensure default behavior of the analyzer does not change.

2020-12-01 14:53 UTC, Evangelink commented
I totally missed this parameter! I will update the PR now

2020-12-01 15:20 UTC, mavasani approved these changes
Thanks @Evangelink!

2020-12-01 15:22 UTC, mavasani commented
@Evangelink Can you please also file a doc issue OR create a doc PR to mention configurability of API surface for https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1068?

2020-12-01 15:23 UTC, mavasani commented
Ah, seems the section is already there and points back to the issue your PR fixes: https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1068#configurability

2020-12-01 15:24 UTC, Evangelink commented
Still needs to be updated, I will file a PR tonight.

2020-12-01 16:02 UTC, merged

2020-12-07 10:58 UTC, Evangelink commented
https://github.com/dotnet/docs/pull/21853