Fix line endings for public api fixers
dotnet/roslyn-analyzers pull request #4774
Opened 2021-02-03 17:10 UTC by Youssef1313

Fixes #4749

2021-02-03 19:18 UTC, sharwell commented on src/PublicApiAnalyzers/Core/CodeFixes/DeclarePublicApiFix.cs
> +            }
❔ Can we make this an extension method? It seems to be used in several places.

2021-02-03 19:19 UTC, sharwell requested changes
* Concept looks good
* Can be improved by the use of an extension method
* Tests are needed

2021-02-04 14:44 UTC, Youssef1313 commented on src/PublicApiAnalyzers/Core/CodeFixes/DeclarePublicApiFix.cs
> -        }
These were used by different code fixes. So I moved them to the new helper class.

2021-02-04 16:57 UTC, Youssef1313 commented
Closing and re-opening to re-run CI due to failing flaky test: https://github.com/dotnet/roslyn-analyzers/issues/4544

2021-02-04 18:34 UTC, sharwell commented on src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
> +        [InlineData("\r")] // macOS line ending.
This was only the Mac line ending prior to OSX. There is no need to support it.

```suggestion
```

2021-02-04 18:37 UTC, sharwell commented on src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
> +        [InlineData("\r")] // macOS line ending.
Mildly interesting side note: the first release of OSX predated .NET Framework 1.0 by almost a year, so C# code should really never need to handle these.

2021-02-05 12:06 UTC, Youssef1313 commented on src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
> +        [Theory]
I expect this test to be fixed on Linux now. Waiting for CI Linux build to confirm.

2021-02-18 22:28 UTC, Evangelink commented
@sharwell Could you review again please?

2021-02-19 05:53 UTC, sharwell approved these changes

2021-02-19 05:54 UTC, merged