Fix CA1805 missing trivia
dotnet/roslyn-analyzers pull request #5531
Opened 2021-09-26 07:44 UTC by wzchua

Fixes https://github.com/dotnet/roslyn-analyzers/issues/5412

2021-09-30 11:34 UTC, NewellClark requested changes
Overall looks good.

2021-09-30 11:34 UTC, NewellClark commented on src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarilyTests.cs
> +        private static VerifyCS.Test GetTestCS(string source, string corrected)
```suggestion
        }
        return;
        
        // Local functions

        private static VerifyCS.Test GetTestCS(string source, string corrected)
```

2021-09-30 13:22 UTC, wzchua commented on src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarilyTests.cs
> +        private static VerifyCS.Test GetTestCS(string source, string corrected)
That's not a local function

2021-10-16 05:50 UTC, Youssef1313 commented on src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarilyTests.cs
> +        }
Would this work?

```suggestion
        private static async Task TestCSAsync(string source, string corrected, params DiagnosticResult[] diagnosticResults)
        {
            var test = new VerifyCS.Test
            {
                TestCode = source,
                LanguageVersion = CodeAnalysis.CSharp.LanguageVersion.Preview,
                FixedCode = corrected,
            };

            test.ExpectedDiagnostics.AddRange(diagnosticResults);
            await test.RunAsync();
        }
```

2021-11-12 02:23 UTC, buyaa-n commented on src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarilyTests.cs
> +using Microsoft.CodeQuality.CSharp.Analyzers.QualityGuidelines;
NIT: I think it is redundant
```suggestion
```

2021-11-12 02:26 UTC, buyaa-n approved these changes
One NIT, overall LGTM, thanks!

2021-11-15 20:25 UTC, merged