CA1810: Report only if field belongs to ctor's type
dotnet/roslyn-analyzers pull request #5812
Opened 2022-01-24 17:25 UTC by Evangelink

Fix #5784

2022-01-24 17:50 UTC, Youssef1313 approved these changes

2022-01-25 03:13 UTC, mavasani commented on src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/InitializeStaticFieldsInlineTests.cs
> +        C1.Size = 42;
What would be the result if the static ctor initializes both static fields of another type and also static fields of the containing type? Would it match our expected result in that case?

2022-01-25 05:59 UTC, sharwell requested changes
Haven't reviewed the implementation, but need to verify this is truly a false positive. CA1810 is a performance analyzer that I don't believe is enabled by default, so we'll want to make sure the analyzer is fully preserving the original intent after this change.

2022-06-24 13:00 UTC, Evangelink commented
@sharwell Please let me know if you think that's better to close PR.

2022-06-27 15:58 UTC, sharwell commented
@Evangelink yep, the analyzer is behaving by design here

2022-06-27 15:58 UTC, closed without merging