Let community-pr workflow has all permissions for `pull_request_target`
dotnet/roslyn-analyzers pull request #6305
Opened 2022-12-08 09:32 UTC by Youssef1313

2022-12-08 16:55 UTC, sharwell requested changes
The repository defaults to no permissions (requires permissions to be explicit). Can you detail what the issue is here?

2022-12-08 17:39 UTC, Youssef1313 commented
@sharwell The problem is that if a member belongs to the dotnet organization, but he sets the visibility to private, the workflow will consider him being a "Community" member.

This PR was to experiment whether giving the actions more permissions will allow it to know whether the person belongs to the organization or not.

I'm not sure though which permission scope will be causing this:

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#assigning-permissions-to-a-specific-job

2022-12-09 06:40 UTC, Youssef1313 commented
I see now that the removal of `permissions` doesn't grant all permissions (the default permissions are changed for this repo). Would you be fine with an explicit write-all to test whether things work or not, then gradually decrease to figure out the "least privilege" required?

2022-12-09 06:40 UTC, closed without merging

2022-12-09 14:33 UTC, sharwell commented
> The problem is that if a member belongs to the dotnet organization, but he sets the visibility to private, the workflow will consider him being a "Community" member.

This is the expected behavior. Users (including Microsoft employees) who do not have write access to the repository are considered community members for triage purposes.

2022-12-09 14:35 UTC, Youssef1313 commented
> who do not have write access

That is not what I'm trying to fix. I'm trying to fix a case where detecting someone who *has* write access doesn't work.

2022-12-09 14:44 UTC, sharwell commented
Do you have an example of such a PR? I'd like to review the query logs.

2022-12-09 14:51 UTC, Youssef1313 commented
@sharwell All @mavasani's PRs. I sent you on Discord the reason I'm suspecting it doesn't work for him.