Generate packages props and targets in `buildTransitive` directory
dotnet/roslyn-analyzers pull request #6325
Opened 2022-12-10 14:11 UTC by Youssef1313

Closes https://github.com/dotnet/roslyn-analyzers/issues/6229

2022-12-20 12:22 UTC, mavasani commented on src/Tools/GenerateAnalyzerNuspec/Program.cs
> +        result.AppendLine(FileElement(fileWithPath, "buildTransitive"));
I am afraid this might break our insertion pipeline of the analyzers into the .NET SDK. @jmarolf definitely needs to review this change.

2022-12-20 12:23 UTC, mavasani requested changes
Shall not be merged before Jon's blessing.

2023-01-09 22:36 UTC, jmarolf commented
Sorry for the delay @Youssef1313. I am going to get a binlog with/without these changes and verify that they are what I expect. I will complete this tomorrow.

2023-01-10 00:07 UTC, jmarolf approved these changes
Confirmed this behavior is correct.

2023-01-10 00:08 UTC, merged

2023-01-12 08:16 UTC, mavasani commented on src/Tools/GenerateAnalyzerNuspec/Program.cs
> +        result.AppendLine(FileElement(fileWithPath, "buildTransitive"));
This seems to have broken mapping AnalysisLevel/AnalysisMode properties to the corresponding globalconfig files in the `build\config` folder. I am preparing a fix as part of another change.