Improved performance of CA1041
dotnet/roslyn-analyzers pull request #6671
Opened 2023-06-06 09:30 UTC by NewellClark

Fix #6143
I've reimplemented it as a syntax-node analyzer, as suggested.

2023-06-07 09:19 UTC, Youssef1313 commented on src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpProvideObsoleteAttributeMessage.cs
> +                return (IdentifierNameSyntax)name;
This might crash for AliasQualifiedNameSyntax or GenericNameSyntax

2023-06-19 04:17 UTC, mavasani requested changes
@NewellClark - thank you for putting the efforts here and creating this PR, it is much appreciated.
However, I believe we need to root cause the performance issue before taking this path. We definitely want analyzer authors to be able to write performant IOperation analyzers when analyzing executable code. I have added a comment in the original issue to help us move forward with the performance investigations.

2023-06-30 16:26 UTC, sharwell commented
💡 We should now be able to use [`IAttributeOperation`](https://github.com/dotnet/roslyn/pull/64488) for this.

2023-06-30 16:44 UTC, Youssef1313 commented
> 💡 We should now be able to use [`IAttributeOperation`](https://github.com/dotnet/roslyn/pull/64488) for this.

This might not work for local functions I think (assuming the original implementation works for local functions)

2023-06-30 17:01 UTC, sharwell commented
I would expect it to work for local functions?

2023-06-30 17:44 UTC, Youssef1313 commented
> I would expect it to work for local functions?

@sharwell `context.ContainingSymbol` will return regular method, IIRC.

2023-06-30 20:49 UTC, sharwell commented
@Youssef1313 it seems like that would not be problematic. The handling will differ slightly for different contexts where this can occur, but in all cases it should be workable.

2025-08-15 11:13 UTC, closed without merging