Enhance: Inline variable in CA1854 (IDictionary.TryGetValue)
dotnet/roslyn-analyzers pull request #7071
Opened 2023-12-07 14:49 UTC by Poker-sang

When simplifying code with `TryGetValue`, we can inline the `out` variable.

Before:
```cs
if (data.TryGetValue(key, out string value))
{
    var a = value;
}
```

After:
```cs
if (data.TryGetValue(key, out string a))
{
}
```

2024-02-22 00:50 UTC, buyaa-n commented on src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpPreferDictionaryTryMethodsOverContainsKeyGuardFixer.cs
> +            string? valueName = null;
NIT: maybe change into `variableName`?

2024-02-22 00:53 UTC, buyaa-n requested changes
Thank you @Poker-sang, the changes looks good, could you please update the [VB fixer](https://github.com/dotnet/roslyn-analyzers/blob/ab13ac75d1195a27e3cf7fb990fc3a51615caa95/src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Performance/BasicPreferDictionaryTryMethodsOverContainsKeyGuardFixer.vb) too? Now this only work on C# but not in VB.

2024-02-22 07:13 UTC, Poker-sang commented
@buyaa-n Thank you for the review. I've never written VB, but I tried writing VB fixer anyway, so I'm not sure if I took all the cases into account. Please let me know if there are any problems.

2024-02-23 01:21 UTC, buyaa-n commented
> I've never written VB, but I tried writing VB fixer anyway, so I'm not sure if I took all the cases into account. Please let me know if there are any problems.

Thanks, most contributors including myself are same, no previous VB experience, https://converter.telerik.com/ have been helpful for converting code and tests in VB, though looks you don't need it now. Changes looks good

2024-02-23 01:24 UTC, buyaa-n commented on src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Performance/BasicPreferDictionaryTryMethodsOverContainsKeyGuardFixer.vb
> +                        generator.DefaultExpression(dictionaryValueType)).
NIT: fix alignment
```suggestion
                                                                    variableName,
                                                                    generator.DefaultExpression(dictionaryValueType)).
````

2024-02-23 01:25 UTC, buyaa-n approved these changes
Looks good, thanks!

2024-02-23 01:51 UTC, merged

2024-02-23 02:19 UTC, Poker-sang commented
> Thanks, most contributors including myself are same, no previous VB experience, https://converter.telerik.com/ have been helpful for converting code and tests in VB, though looks you don't need it now. Changes looks good

Thanks. I use <https://sharplab.io/> to see the C#/VB syntax tree. The site you recommended looks good too, I'll try it.