Exclude exception types from CA1515
dotnet/roslyn-analyzers pull request #7234
Opened 2024-03-07 23:30 UTC by CollinAlpert

Affected analyzer: MakeTypesInternal
Affected diagnostic ID: [CA1515](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1515)

This PR ensures that exception types are not suggested to be made internal, as this could conflict with [CA1064](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1064).

Fixes #7191

2024-06-18 18:19 UTC, buyaa-n requested changes
Thank you @CollinAlpert for the fix, as [discussed in the issue](https://github.com/dotnet/roslyn-analyzers/issues/7191#issuecomment-2153878116) we don't want to exclude exception types from CA1515, instead it's better to exclude diagnostic for [CA1064 Exceptions should be public:](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1064) in executable. 

- Please revert the `Exclude exception types from CA1515` part from the PR, looks you also did some code refactoring for the analyzer we can accept that part.
- If you are interested fixing the issue by excluding CA1064 diagnostics for executable, that will be great, but not required

2024-06-19 19:45 UTC, CollinAlpert commented
Thanks for the hint, I have reverted the change to CA1515 and tweaked CA1064.

2024-06-21 18:09 UTC, buyaa-n reviewed
Left a few comments, overall looks great, thank you @CollinAlpert!

2024-06-23 18:47 UTC, CollinAlpert commented on src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/MakeTypesInternal.cs
>                      return;
`MakeTypesInternal` allows configuring the `OutputKind`s via `.editorconfig`, something `ExceptionsShouldBePublicAnalyzer` does not. This is why the check is a bit more complicated.

2024-06-23 18:54 UTC, CollinAlpert commented on src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/MakeTypesInternal.cs
> +        /// <see cref="Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.ExceptionsShouldBePublicAnalyzer"/>
Good point, I removed it.

2024-06-24 16:03 UTC, buyaa-n approved these changes
Thanks @CollinAlpert looks good

2024-06-24 16:03 UTC, merged